version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nest-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nest_development
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password123
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nest-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nest-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nest.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - nest-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  nest-network:
    driver: bridge